namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
namespace: prodd
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
